### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchFieldException: model

### ISSUE THREAD

**Issue by vorburger** [heeckhau/mousefeed#4]
Hello @heeckhau do you still actively maintain mousefeed?

I was considering including it in https://github.com/vorburger/opendaylight-eclipse-setup, and tested it out a bit today, but found that it breaks e.g. with EGit's Team > Pull. EGit's Pull does not work anymore when the error below appears, so this is a bit of a show stopper for using mousefeed of course.

Versions are Eclipse 4.6 Neon Release Candidate 2 (4.6.0RC2) Build id: 20160526-1324 with EGit Eclipse Git Team Provider 4.4.0.201605250940-rc1.

Maybe mousefeed could somehow be made a little more robust to at least not prevent working functionality of other plugins to break even if it is having trouble to find the keyboard shortcut?

```
java.lang.RuntimeException: java.lang.NoSuchFieldException: model
	at com.mousefeed.eclipse.HandledContributionItemCommandLocator.getModelField(HandledContributionItemCommandLocator.java:100)
	at com.mousefeed.eclipse.HandledContributionItemCommandLocator.getItemParCommand(HandledContributionItemCommandLocator.java:72)
	at com.mousefeed.eclipse.HandledContributionItemCommandLocator.get(HandledContributionItemCommandLocator.java:57)
	at com.mousefeed.eclipse.HandledActionDescGenerator.generate(HandledActionDescGenerator.java:70)
	at com.mousefeed.eclipse.GlobalSelectionListener.processContributionItem(GlobalSelectionListener.java:142)
	at com.mousefeed.eclipse.GlobalSelectionListener.handleEvent(GlobalSelectionListener.java:119)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1594)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1339)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4542)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1119)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1020)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: java.lang.NoSuchFieldException: model
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at com.mousefeed.eclipse.HandledContributionItemCommandLocator.getModelField(HandledContributionItemCommandLocator.java:94)
	... 32 more
```

**Comment by vorburger** [comment]
Even a simple menu File > Restart (no EGit) causes something like above on Neon 4.6.

**Comment by heeckhau** [comment]
I'll check

**Comment by heeckhau** [comment]
Can you try again with the 2.0.3 release?

**Comment by vorburger** [comment]
@heeckhau sorry for the delay, I've just tried with 2.0.3 and it looks like this is fine now - tx! Thus closing this.

https://github.com/vorburger/opendaylight-eclipse-setup/commit/9409f76b0118b2f746669acb43fb3a00e110bbd6#diff-c6b57d6f928ec9659aedc6d9298e9ce9R596 brings mousefeed into https://github.com/vorburger/opendaylight-eclipse-setup !
